// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package digitalid_sdk.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONObject;

public class JA_JSON_toArr extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String str_json;

	public JA_JSON_toArr(IContext context, java.lang.String str_json)
	{
		super(context);
		this.str_json = str_json;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject>ret=new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject>();
		JSONObject o=new JSONObject(str_json);
		o.keys().forEachRemaining(k->{
			Object v=o.get(k);
			com.mendix.systemwideinterfaces.core.IMendixObject mxo=com.mendix.core.Core.instantiate(this.getContext(),"DigitalID_SDK.KeyValue");
			mxo.setValue(this.getContext(),"Key",k);
			mxo.setValue(this.getContext(),"Value",v);
			ret.add(mxo);
			//com.mendix.core.Core.getLogger(this.toString()).info("Key: {0}\tValue: {1}", key, value);
		});
		return ret;//new JSONObject(str_val).getString(str_k);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_JSON_toArr";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
