// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package digitalid_sdk.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.thirdparty.org.json.JSONObject;

/**
 * Simple action to do single level key lookup on a JSON object
 */
public class JA_JSON_getKey extends CustomJavaAction<java.lang.String>
{
	private java.lang.String str_val;
	private java.lang.String str_k;

	public JA_JSON_getKey(IContext context, java.lang.String str_val, java.lang.String str_k)
	{
		super(context);
		this.str_val = str_val;
		this.str_k = str_k;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		//return new JSONObject(str_val).getString(str_k);
		JSONObject obj=new JSONObject(str_val);
		Object value=obj.get(str_k);
		if(value instanceof JSONObject){
			return value.toString();
		}else{
			return value.toString();
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_JSON_getKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
