// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package digitalid_sdk.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.net.URLDecoder;
import java.net.URLEncoder;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.thirdparty.org.json.JSONException;

/**
 * Twilio calls webhooks with form data. To make this usable, we can convert it to json using this Java action
 */
public class JA_QueryParams_toJSON extends CustomJavaAction<java.lang.String>
{
	private java.lang.String str_val;

	public JA_QueryParams_toJSON(IContext context, java.lang.String str_val)
	{
		super(context);
		this.str_val = str_val;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		JSONObject object=new JSONObject();
		String[]kvbuf=str_val.split("\\&");
		for(int i=0;i<kvbuf.length;i++){
			String k=URLDecoder.decode(kvbuf[i].split("=")[0],"UTF-8");
			String v=URLDecoder.decode(kvbuf[i].split("=")[1],"UTF-8");
			try{
				if(this.isjson(v)){
					if(v.startsWith("{")){
						object.put(k,new JSONObject(v));
					}else{
						object.put(k,new JSONArray(v));
					}
					
				}else{
					object.put(k,v);
				}
			}catch(Exception e){
				object.put(k,v);
			}
		};
		String jsonString=object.toString(2);
		return jsonString;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_QueryParams_toJSON";
	}

	// BEGIN EXTRA CODE
	//https://stackoverflow.com/questions/10174898/how-to-check-whether-a-given-string-is-valid-json-in-java
	//https://stackoverflow.com/questions/28130285/unhandled-exception-org-json-jsonexception
	public boolean isjson(String test){
		try{
			new JSONObject(test);
		}catch(JSONException ex){
			try{
				new JSONArray(test);
			}catch(JSONException ex1){
				return false;
			}
		}
		return true;
	}
	// END EXTRA CODE
}
